version: 2.1

orbs:
  badges: rhems-japan/badges@0.0.1

commands:
  setup_ssh_keys:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a0:b1:c2:d3:e4:f5:a6:b7:c8:d9:ea:fb:0c:1d:2e:55"

jobs:
  job_name:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_ssh_keys
      - checkout
      - badges/create_badge:
          app: "test"
          color: "orange"
          test: "v2"
      - badges/update_readme
