version: 2.1

orbs:
  badges: rhems-japan/badges@0.0.1

commands:
  setup_ssh_keys:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "be:ac:f7:87:be:03:f2:e3:7e:35:6e:88:03:dc:c9:21"

jobs:
  change_readme:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_ssh_keys
      - checkout
      - badges/create_badge
          # app: "test"
          # color: "orange"
          # test: "v2"
      - badges/update_readme

workflows:
  run:
    jobs:
      - change_readme
